services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: malaow
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
        - pokebin

  web:
    build: .
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    network_mode: host
    # networks:
    #     - pokebin

networks:
  pokebin:
