pub const ARRAY_LIST_INITIAL_CAPACITY_SM: usize = 64;
pub const ARRAY_LIST_INITIAL_CAPACITY_MD: usize = 128;
pub const ARRAY_LIST_INITIAL_CAPACITY_LG: usize = 256;
pub const ARRAY_LIST_INITIAL_CAPACITY_XL: usize = 512;
pub const ARRAY_LIST_INITIAL_CAPACITY_XXL: usize = 1024;
